
drop DATABASE FUT_DB;
CREATE DATABASE FUT_DB;
USE FUT_DB;

-- TABELA ARBITRO

CREATE TABLE ARBITRO
(
	 CODARBITRO  INTEGER NOT NULL,
	 CODTEMPORADA  INTEGER NOT NULL,
	 NOMEARBITRO  VARCHAR(150),
	 DATANASCIMENTO  DATE,
	 FOTO  LONGBLOB, 
	PRIMARY KEY ( CODARBITRO )
);

-- TABELA CAMPEONATO

CREATE TABLE  CAMPEONATO
(
	 CODCAMPEONATO  INTEGER NOT NULL,
	 NOME  VARCHAR(150) NOT NULL,
	 TIPO  INTEGER NOT NULL,
	 PAIS  VARCHAR(30),
	 ESCUDO  LONGBLOB,
	PRIMARY KEY ( CODCAMPEONATO )
);

-- TABELA CLASSIFICAÇÃO

CREATE TABLE  CLASSIFICACAO 
(
	 CODCLASSIFICACAO  INTEGER NOT NULL,
	 CODESTRUTURATEMPORADA  INTEGER NOT NULL,
	 DATAJOGO  DATE NOT NULL,
	 CODEQUIPE  INTEGER NOT NULL,
	 PONTOS  INTEGER default 0,
	 VITORIA  INTEGER default 0,
	 EMPATE  INTEGER default 0,
	 DERROTA  INTEGER default 0,
	 VITORIAPRORROGACAO INTEGER default 0,
	 VITORIAPENALTIS  INTEGER default 0,
	 DERROTAPRORROGACAO INTEGER default 0,
	 DERROTAPENALTIS  INTEGER default 0,
	 GOLSPRO  INTEGER default 0,
	 GOLSCONTRA  INTEGER default 0,
	 SALDOGOLS INTEGER AS (GolsPro - GolsContra),
	 PUBLICO  INTEGER,
	 LOCAL  VARCHAR(1) NOT NULL,
	 REALIZADO  INTEGER NOT NULL,
	 JOGOS  INTEGER,
	 EMPATEPRORROGACAO  INTEGER,
	PRIMARY KEY ( CODCLASSIFICACAO )
);


-- TABELA EQUIPE

CREATE TABLE  EQUIPE 

(
 CODEQUIPE  INTEGER NOT NULL,
 NOMEEQUIPE  VARCHAR(50) NOT NULL,
 NOMECOMPLETOEQUIPE VARCHAR(200),
 DATAFUNDACAO  DATE,
 CIDADE  VARCHAR(30),
 PAIS  VARCHAR(30),
 TIPOEQUIPE  INTEGER,
 ESCUDO  LONGBLOB ,
 CODESTADIO  INTEGER,
PRIMARY KEY ( CODEQUIPE )
);

-- TABELA EQUIPECOMPETETEMPORADA

CREATE TABLE  EQUIPECOMPETETEMPORADA 
(
 CODEQUIPE  INTEGER NOT NULL,
 CODTEMPORADA  INTEGER NOT NULL,
PRIMARY KEY ( CODEQUIPE ,  CODTEMPORADA )
);

-- TABELA ESCALACAOJOGO

CREATE TABLE  ESCALACAOJOGO 
(
 CODJOGO  INTEGER NOT NULL,
 CODEQUIPE  INTEGER NOT NULL,
 CODJOGADOR  INTEGER NOT NULL,
 CODJOGADORENTROU  INTEGER,
 STATUS  VARCHAR(1),
 SAIU  VARCHAR(1),
 TEMPOJOGADO  INTEGER,
 MINUTOSUBSTITUICAO INTEGER,
PRIMARY KEY ( CODJOGO ,  CODEQUIPE ,  CODJOGADOR )
);

-- TABELA ESTADIO

CREATE TABLE  ESTADIO 
(
 CODESTADIO  INTEGER NOT NULL,
 NOMEESTADIO  VARCHAR(50) NOT NULL,
 NOMECOMPLETOESTADIO  VARCHAR(200),
 CAPACIDADEESTADIO  INTEGER,
 CIDADEESTADIO  VARCHAR(30),
 FOTO  LONGBLOB ,
 PAIS  VARCHAR(30),
PRIMARY KEY ( CODESTADIO )
);

-- TABELA ESTRUTURATEMPORADA

CREATE TABLE  ESTRUTURATEMPORADA 
(
 CODESTRUTURATEMPORADA  INTEGER NOT NULL,
 CODTEMPORADA  INTEGER NOT NULL,
 NOMEESTRUTURATEMPORADA  VARCHAR(30) NOT NULL,

 CODGRUPO  INTEGER,
 CODFASE  INTEGER,
PRIMARY KEY ( CODESTRUTURATEMPORADA )
);

-- TABELA GERADOR

CREATE TABLE  GERADOR 
(
 OID  INTEGER NOT NULL,
PRIMARY KEY ( OID )
);

-- TABELA JOGADOR

CREATE TABLE  JOGADOR 
(
 CODJOGADOR  INTEGER NOT NULL,
 CODEQUIPE  INTEGER NOT NULL,
 CODTEMPORADA  INTEGER NOT NULL,
 APELIDOJOGADOR  VARCHAR(150) NOT NULL,
 NOMEJOGADOR  VARCHAR(150),
 NUMEROCAMISA  INTEGER,
 DATANASCIMENTO  DATE,
 NACIONALIDADE  VARCHAR(30),
 POSICAO  INTEGER,
 STATUS  VARCHAR(1) default  "A" ,
 EMAIL  VARCHAR(100),
 FOTO  LONGBLOB ,
PRIMARY KEY ( CODJOGADOR )
);
-- TABELA JOGO

CREATE TABLE  JOGO 
(
 CODJOGO  INTEGER NOT NULL,
 CODESTRUTURATEMPORADA  INTEGER NOT NULL,
 CODEQUIPECASA  INTEGER NOT NULL,
 CODEQUIPEFORA  INTEGER NOT NULL,
 TV  VARCHAR(10),
 NOMEESTADIO  VARCHAR(30),
 GOLSTIMECASA  INTEGER,
 GOLSTIMEFORA  INTEGER,
 GOLSTIMECASAPRITEM INTEGER,
 GOLSTIMEFORAPRITEM INTEGER,
 PRORROGACAO  INTEGER default 0,
 PENALTIS  INTEGER default 0,
 GOLSTIMECASAPRORROGACAO  INTEGER,
 GOLSTIMEFORAPRORROGACAO  INTEGER,
 GOLSTIMECASAPENALTIS  INTEGER,
 GOLSTIMEFORAPENALTIS  INTEGER,
 PUBLICO  INTEGER,
 NOTICIA  LONGBLOB ,
 REALIZADO  INTEGER NOT NULL,
 ESTATCHUTECASA  INTEGER default 0,
 ESTATCHUTEFORA  INTEGER default 0,
 ESTATFALTACASA  INTEGER default 0,
 ESTATFALTAFORA  INTEGER default 0,
 ESTATESCANTEIOCASA INTEGER default 0,
 ESTATESCANTEIOFORA INTEGER default 0,
 ESTATIMPEDIMENTOCASA  INTEGER default 0,
 ESTATIMPEDIMENTOFORA  INTEGER default 0,
 DATAHORAJOGO  TIMESTAMP,
 CODARBITRO  INTEGER,
 CODESTADIO  INTEGER,

 FOTO1  LONGBLOB ,
 FOTO2  LONGBLOB,
 CODCLASSIFICACAOTIMECASA  INTEGER NOT NULL,
 CODCLASSIFICACAOTIMEFORA  INTEGER NOT NULL,
PRIMARY KEY ( CODJOGO )
);

-- TABELA LANCEPARTIDA

CREATE TABLE  LANCEPARTIDA 
(
 CODLANCEPARTIDA  INTEGER NOT NULL,
 CODJOGO  INTEGER NOT NULL,
 CODJOGADOR  INTEGER NOT NULL,
 TIPOLANCE  INTEGER NOT NULL,
 MINUTO  INTEGER,
 CODEQUIPELANCE  INTEGER NOT NULL,
 CODEQUIPEJOGADOR  INTEGER NOT NULL,
PRIMARY KEY ( CODLANCEPARTIDA )
);

-- TABELA NARRACAO

CREATE TABLE  NARRACAO 
(
 CODNARRACAO  INTEGER NOT NULL,
 CODJOGO  INTEGER NOT NULL,
 MINUTO  INTEGER,
 NARRACAO  LONGBLOB,
PRIMARY KEY ( CODNARRACAO )
);

-- TABELA PUNICAO

CREATE TABLE  PUNICAO 
(
 CODPUNICAO  INTEGER NOT NULL,
 CODESTRUTURATEMPORADA  INTEGER NOT NULL,
 CODEQUIPE  INTEGER NOT NULL,
 PONTOS  INTEGER NOT NULL,
 MOTIVO  VARCHAR(100),
 DATA  DATE,
 CODCLASSIFICACAO  INTEGER NOT NULL,
PRIMARY KEY ( CODPUNICAO )
);

-- TABELA TEMPORADA
CREATE TABLE  TEMPORADA 
(
 CODTEMPORADA  INTEGER NOT NULL,
 CODCAMPEONATO  INTEGER NOT NULL,
 NOMETEMPORADA  VARCHAR(150) NOT NULL,
 PONTOSVITORIA  INTEGER default 3,
 PONTOSEMPATE  INTEGER default 1,
 PONTOSVITORIAPRORROGACAO  INTEGER default 0,

 PONTOSVITORIAPENALTIS  INTEGER default 0,
 PONTOSDERROTAPRORROGACAO  INTEGER default 0,
 PONTOSDERROTAPENALTIS  INTEGER default 0,
 DESCRICAO  LONGBLOB,
 NUMTIMEREBAIXADO  INTEGER default 0,
 NUMTIMEPROMOVIDO  INTEGER default 0,
 PONTOSEMPATEPRORROGACAO  INTEGER,
 SQLDESEMPATE  VARCHAR(100) NOT NULL,
 NUMTIMECOMPET1  INTEGER NOT NULL,
 NUMTIMECOMPET2  INTEGER NOT NULL,
 NUMTIMEPOREBAIXAMENTO  INTEGER NOT NULL,
PRIMARY KEY ( CODTEMPORADA )
);

ALTER TABLE  TEMPORADA  ADD FOREIGN KEY ( CODCAMPEONATO ) REFERENCES  CAMPEONATO ( CODCAMPEONATO );

ALTER TABLE  CLASSIFICACAO  ADD FOREIGN KEY ( CODESTRUTURATEMPORADA ) REFERENCES ESTRUTURATEMPORADA  ( CODESTRUTURATEMPORADA );
 
ALTER TABLE  CLASSIFICACAO  ADD FOREIGN KEY ( CODEQUIPE ) REFERENCES  EQUIPE ( CODEQUIPE );

ALTER TABLE  CLASSIFICACAO  ADD FOREIGN KEY ( CODESTRUTURATEMPORADA ) REFERENCES ESTRUTURATEMPORADA  ( CODESTRUTURATEMPORADA );

ALTER TABLE  ARBITRO  ADD FOREIGN KEY ( CODTEMPORADA ) REFERENCES  TEMPORADA ( CODTEMPORADA );

ALTER TABLE  PUNICAO  ADD FOREIGN KEY ( CODESTRUTURATEMPORADA ) REFERENCES ESTRUTURATEMPORADA  ( CODESTRUTURATEMPORADA );
 
ALTER TABLE  PUNICAO  ADD FOREIGN KEY ( CODEQUIPE ) REFERENCES  EQUIPE  ( CODEQUIPE );

ALTER TABLE  NARRACAO  ADD FOREIGN KEY ( CODJOGO ) REFERENCES  JOGO  ( CODJOGO );

ALTER TABLE  LANCEPARTIDA  ADD FOREIGN KEY ( CODEQUIPELANCE ) REFERENCES  EQUIPE( CODEQUIPE );

ALTER TABLE  LANCEPARTIDA  ADD FOREIGN KEY ( CODJOGO ) REFERENCES  JOGO  ( CODJOGO );

ALTER TABLE  LANCEPARTIDA  ADD FOREIGN KEY ( CODJOGADOR ) REFERENCES  JOGADOR ( CODJOGADOR );

ALTER TABLE  JOGO  ADD FOREIGN KEY ( CODESTRUTURATEMPORADA ) REFERENCES ESTRUTURATEMPORADA  ( CODESTRUTURATEMPORADA );
 
ALTER TABLE  JOGO  ADD FOREIGN KEY ( CODEQUIPECASA ) REFERENCES  EQUIPE  ( CODEQUIPE );

ALTER TABLE  JOGADOR  ADD FOREIGN KEY ( CODEQUIPE ) REFERENCES  EQUIPE  ( CODEQUIPE );

ALTER TABLE  JOGADOR  ADD FOREIGN KEY ( CODTEMPORADA ) REFERENCES  TEMPORADA ( CODTEMPORADA );

ALTER TABLE  ESTRUTURATEMPORADA  ADD FOREIGN KEY ( CODTEMPORADA ) REFERENCES  TEMPORADA ( CODTEMPORADA );

ALTER TABLE  EQUIPECOMPETETEMPORADA  ADD FOREIGN KEY ( CODEQUIPE ) REFERENCES  EQUIPE ( CODEQUIPE );

ALTER TABLE  EQUIPECOMPETETEMPORADA  ADD FOREIGN KEY ( CODTEMPORADA ) REFERENCES TEMPORADA  ( CODTEMPORADA );

ALTER TABLE  ESCALACAOJOGO  ADD FOREIGN KEY ( CODJOGO ) REFERENCES  JOGO  ( CODJOGO );

ALTER TABLE  ESCALACAOJOGO  ADD FOREIGN KEY ( CODEQUIPE ) REFERENCES  EQUIPE ( CODEQUIPE );

ALTER TABLE  ESCALACAOJOGO  ADD FOREIGN KEY ( CODJOGADOR ) REFERENCES  JOGADOR ( CODJOGADOR );

ALTER TABLE  ESCALACAOJOGO  ADD FOREIGN KEY ( CODJOGADORENTROU ) REFERENCES  JOGADOR ( CODJOGADOR );
